### ISSUE TITLE
Scriere cale pentru fisierul date.txt

### ISSUE THREAD

**Issue by ioanstoica** [StoicaIoan02/oop#1]
https://github.com/StoicaIoan02/oop/blob/6b63f20cdc010c57679d2d4ac58c70a9c753f336/src/coin.cpp#L76

Am mutat fisierul date.txt in folderul date. Am modificat calea, dar tot nu il vede. De ce?

@mcmarius

**Comment by mcmarius** [comment]
Te referi că nu îl vede pe gh actions sau local? Pe gh actions trebuie modificat în .github/workflows/cmake.yml  la liniile 267 și 274 (sper că nu greșesc) și pus date/date.txt în loc de date.txt
