### ISSUE TITLE
Eroare la 4 joburi - "implicitly-declared ‘utility_token::utility_token(const utility_token&)’ is deprecated"

### ISSUE THREAD

**Issue by ioanstoica** [StoicaIoan02/oop#2]
https://github.com/StoicaIoan02/oop/blob/90070d74970828ad31b5527c03956abeb21aebf7/src/utility_token.cpp#L20

Primesc erori in gh actions la operatorul = de la clasa derivata "utility_token", iar in CodeBlocks îmi merge . Cum trebuie scris sa supraîncarc operatorul ca sa nu mai dea eroare?

@mcmarius

**Comment by mcmarius** [comment]
`utility_token& utility_token::operator = ( const utility_token& x)`

dar nu de la asta dă eroare, ci pt că ai definit op=, dar nu ai definit și cc; de obicei, ori le suprascrii pe ambele, ori pe niciunul; dacă suprascrii doar cc sau doar op=, e posibil ca pe viitor compilatorul să nu mai genereze și cealaltă funcție specială și de-asta dă warning (care e transformat în eroare)
